local:
    repo_path: ../trip2
    base_path: /var/www/trip2
    public_path: /var/www/trip2/public
    db_password: secret
digital_ocean:
    base_path: /var/www/trip2
    public_path: /var/www/trip2/public
    db_password: secret
    token: ''
    plan: '512mb'
linode:
    base_path: /var/www/trip2
    public_path: /var/www/trip2/public
    db_password: secret
    token: ''
    plan: 'Linode 1024'