# General config

environment: local
db_password: secret

# Local config

trip_folder: '../trip2'

# Cloud provider config
# Plans for Digital Ocean: '512mb', '1gb' etc
# Plans for Linode: 'Linode 1024', 'Linode 2048' etc

plan: ''
token: ''
label: ''

# Deploy config

slack:

# Papertrail config

papertrail_domain:
papertrail_port:

# Mail config

mail_username:
mail_password:
